<?php
/**
 * Market Intelligence Platform - Web Installer
 * 
 * Access via: https://yourdomain.com/install.php
 * DELETE THIS FILE after installation!
 */

// Pre-fill known values
$prefill = [
    'db_host' => 'localhost',
    'db_name' => 'u983353360_sm',
    'db_user' => 'u983353360_sm',
    'db_pass' => 'fafTKpQ&o1',
    'admin_user' => 'admin',
    'admin_pass' => 'Admin@123456',
    'admin_email' => 'admin@example.com'
];

$step = $_POST['step'] ?? 1;
$step = (int) $step;
$errors = [];
$success = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($step === 2) {
        // Step 2: Test DB connection and write env.php
        $dbHost = trim($_POST['db_host'] ?? 'localhost');
        $dbName = trim($_POST['db_name'] ?? '');
        $dbUser = trim($_POST['db_user'] ?? '');
        $dbPass = $_POST['db_pass'] ?? '';
        $dbCharset = 'utf8mb4';

        if (empty($dbName) || empty($dbUser)) {
            $errors[] = 'اسم قاعدة البيانات واسم المستخدم مطلوبان';
            $step = 1;
        } else {
            try {
                $pdo = new PDO(
                    "mysql:host={$dbHost};charset={$dbCharset}",
                    $dbUser,
                    $dbPass,
                    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
                );

                // Create database if not exists
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                $pdo->exec("USE `{$dbName}`");

                // Write env.php
                $envContent = "<?php\n";
                $envContent .= "/**\n * Environment Configuration - Auto-generated by installer\n */\n\n";
                $envContent .= "// Database\n";
                $envContent .= "define('DB_HOST', '{$dbHost}');\n";
                $envContent .= "define('DB_NAME', '{$dbName}');\n";
                $envContent .= "define('DB_USER', '{$dbUser}');\n";
                $envContent .= "define('DB_PASS', '{$dbPass}');\n\n";
                $envContent .= "// Apify (configure later from Settings page)\n";
                $envContent .= "// define('APIFY_API_TOKEN', 'your_apify_token');\n";
                $envContent .= "// define('APIFY_ACTOR_ID', 'scraply~x-twitter-posts-search');\n\n";
                $envContent .= "// OpenAI (configure later from Settings page)\n";
                $envContent .= "// define('OPENAI_API_KEY', 'your_openai_key');\n";
                $envContent .= "// define('OPENAI_MODEL', 'gpt-4o-mini');\n\n";

                $adminUser = trim($_POST['admin_user'] ?? 'admin');
                $adminPass = $_POST['admin_pass'] ?? 'Admin@123456';
                $adminEmail = trim($_POST['admin_email'] ?? 'admin@example.com');

                $envContent .= "// Admin user\n";
                $envContent .= "define('ADMIN_USERNAME', '{$adminUser}');\n";
                $envContent .= "define('ADMIN_PASSWORD', '{$adminPass}');\n";
                $envContent .= "define('ADMIN_EMAIL', '{$adminEmail}');\n";

                $envPath = dirname(__DIR__) . '/config/env.php';
                $written = file_put_contents($envPath, $envContent);

                if ($written !== false) {
                    $success[] = 'تم حفظ إعدادات قاعدة البيانات بنجاح';
                    $success[] = 'تم إنشاء قاعدة البيانات ' . $dbName;
                    $_SESSION['install_db_ok'] = true;
                    $_SESSION['install_db_host'] = $dbHost;
                    $_SESSION['install_db_name'] = $dbName;
                    $_SESSION['install_db_user'] = $dbUser;
                    $_SESSION['install_db_pass'] = $dbPass;
                } else {
                    $errors[] = 'فشل كتابة ملف config/env.php - تحقق من صلاحيات الملفات';
                    $step = 1;
                }
            } catch (PDOException $e) {
                $errors[] = 'فشل الاتصال بقاعدة البيانات: ' . $e->getMessage();
                $step = 1;
            }
        }
    }

    if ($step === 3) {
        // Step 3: Import schema
        $dbHost = $_SESSION['install_db_host'] ?? 'localhost';
        $dbName = $_SESSION['install_db_name'] ?? '';
        $dbUser = $_SESSION['install_db_user'] ?? '';
        $dbPass = $_SESSION['install_db_pass'] ?? '';

        try {
            $pdo = new PDO(
                "mysql:host={$dbHost};dbname={$dbName};charset=utf8mb4",
                $dbUser,
                $dbPass,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );

            $schemaFile = dirname(__DIR__) . '/database/schema.sql';
            if (!file_exists($schemaFile)) {
                $errors[] = 'ملف schema.sql غير موجود';
                $step = 2;
            } else {
                $schema = file_get_contents($schemaFile);
                $statements = array_filter(
                    array_map('trim', explode(';', $schema)),
                    function($s) { return !empty($s) && $s !== ';'; }
                );

                $importErrors = 0;
                foreach ($statements as $stmt) {
                    try {
                        $pdo->exec($stmt);
                    } catch (PDOException $e) {
                        if (strpos($e->getMessage(), 'already exists') === false) {
                            $importErrors++;
                        }
                    }
                }

                $success[] = 'تم استيراد هيكل قاعدة البيانات بنجاح (' . count($statements) . ' عبارة)';
                if ($importErrors > 0) {
                    $success[] = "تنبيه: {$importErrors} أخطاء تم تجاهلها (جداول موجودة مسبقاً)";
                }
                $_SESSION['install_schema_ok'] = true;
            }
        } catch (PDOException $e) {
            $errors[] = 'خطأ في الاتصال: ' . $e->getMessage();
            $step = 2;
        }
    }

    if ($step === 4) {
        // Step 4: Create admin user + seed data
        define('APP_ROOT', dirname(__DIR__));
        require_once APP_ROOT . '/config/config.php';
        require_once APP_ROOT . '/app/core/Database.php';
        require_once APP_ROOT . '/app/core/Auth.php';

        $db = Database::getInstance();
        if (!$db->isConnected()) {
            $errors[] = 'فشل الاتصال بقاعدة البيانات';
            $step = 3;
        } else {
            // Create admin
            $userId = Auth::createAdmin();
            $success[] = 'تم إنشاء حساب المدير (ID: ' . $userId . ')';

            // Seed sample data if requested
            if (!empty($_POST['seed_data'])) {
                require_once APP_ROOT . '/app/core/Helpers.php';
                require_once APP_ROOT . '/app/models/ProjectModel.php';
                require_once APP_ROOT . '/app/models/PostModel.php';
                require_once APP_ROOT . '/app/models/AlertModel.php';
                require_once APP_ROOT . '/app/models/SummaryModel.php';

                $seedFile = APP_ROOT . '/database/seed.php';
                // The seed.php will be run via include which executes it
                // But we need to prevent its echo output, so let's do it manually

                $project = $db->queryOne("SELECT id FROM projects WHERE name = 'شركة النخبة للخدمات'");
                if (!$project) {
                    $projectId = $db->insert('projects', [
                        'name' => 'شركة النخبة للخدمات',
                        'description' => 'شركة رائدة في مجال الخدمات والاستشارات',
                        'is_active' => 1,
                        'created_at' => date('Y-m-d H:i:s'),
                        'updated_at' => date('Y-m-d H:i:s')
                    ]);

                    $keywords = ['النخبة', 'خدمات النخبة', 'شركة النخبة'];
                    foreach ($keywords as $kw) {
                        $db->insert('project_keywords', ['project_id' => $projectId, 'keyword' => $kw, 'type' => 'search']);
                    }
                    $crisisKw = ['فضيحة النخبة', 'مقاطعة النخبة', 'احتيال'];
                    foreach ($crisisKw as $kw) {
                        $db->insert('project_keywords', ['project_id' => $projectId, 'keyword' => $kw, 'type' => 'crisis']);
                    }
                    $hashtags = ['#النخبة', '#خدمات_النخبة', '#شركة_النخبة'];
                    foreach ($hashtags as $ht) {
                        $db->insert('project_hashtags', ['project_id' => $projectId, 'hashtag' => $ht]);
                    }
                    $accounts = ['@alnokhba', '@nokhba_services'];
                    foreach ($accounts as $acc) {
                        $db->insert('project_accounts', ['project_id' => $projectId, 'account_username' => $acc]);
                    }
                    $db->insert('competitors', ['project_id' => $projectId, 'name' => 'المنافس الذهبي', 'username' => '@golden_competitor']);

                    $runId = $db->insert('collection_runs', [
                        'project_id' => $projectId,
                        'actor_id' => 'scraply~x-twitter-posts-search',
                        'status' => 'completed',
                        'targets' => json_encode(['النخبة', '#النخبة', '@alnokhba'], JSON_UNESCAPED_UNICODE),
                        'posts_found' => 30,
                        'posts_stored' => 30,
                        'started_at' => date('Y-m-d H:i:s', strtotime('-1 hour')),
                        'completed_at' => date('Y-m-d H:i:s'),
                        'created_at' => date('Y-m-d H:i:s'),
                        'updated_at' => date('Y-m-d H:i:s')
                    ]);

                    // Sample posts
                    $samplePosts = [
                        ['text' => 'خدمة ممتازة من شركة النخبة، أنصح الجميع بالتعامل معهم', 'sentiment' => 'positive', 'score' => 85, 'rep' => 'praise', 'topic' => 'service', 'risk' => 5, 'likes' => 120, 'replies' => 15, 'reposts' => 30, 'views' => 5000],
                        ['text' => 'تأخير رهيب في التوصيل! انتظرت أسبوع كامل بدون أي رد', 'sentiment' => 'negative', 'score' => 15, 'rep' => 'complaint', 'topic' => 'delay', 'risk' => 60, 'likes' => 250, 'replies' => 80, 'reposts' => 45, 'views' => 12000, 'complaint' => 1],
                        ['text' => 'شركة النخبة أعلنت عن عرض جديد الصيف، أسعار منافسة', 'sentiment' => 'neutral', 'score' => 50, 'rep' => 'neutral_mention', 'topic' => 'campaign', 'risk' => 10, 'likes' => 50, 'replies' => 5, 'reposts' => 20, 'views' => 3000],
                        ['text' => 'هل صحيح أن النخبة رفعت الأسعار بشكل كبير؟', 'sentiment' => 'neutral', 'score' => 40, 'rep' => 'inquiry', 'topic' => 'pricing', 'risk' => 35, 'likes' => 30, 'replies' => 12, 'reposts' => 8, 'views' => 2000],
                        ['text' => 'فضيحة! شركة النخبة تبيع بيانات العملاء لأطراف ثالثة #مقاطعة_النخبة', 'sentiment' => 'negative', 'score' => 5, 'rep' => 'rumor', 'topic' => 'management', 'risk' => 90, 'likes' => 500, 'replies' => 200, 'reposts' => 150, 'views' => 50000, 'crisis' => 1, 'attack' => 1],
                        ['text' => 'هاهاها شركة النخبة بتقول خدمات ممتازة 😂 والواقع عكس كذا', 'sentiment' => 'negative', 'score' => 20, 'rep' => 'sarcasm', 'topic' => 'service', 'risk' => 45, 'likes' => 180, 'replies' => 40, 'reposts' => 60, 'views' => 8000, 'sarcasm' => 1],
                        ['text' => 'الدعم الفني في النخبة سريع الاستجابة وحلوا مشكلتي بسرعة', 'sentiment' => 'positive', 'score' => 80, 'rep' => 'praise', 'topic' => 'support', 'risk' => 5, 'likes' => 40, 'replies' => 8, 'reposts' => 10, 'views' => 1500],
                        ['text' => 'هجوم منسق على شركة النخبة من حسابات وهمية', 'sentiment' => 'negative', 'score' => 10, 'rep' => 'attack', 'topic' => 'competition', 'risk' => 75, 'likes' => 90, 'replies' => 30, 'reposts' => 25, 'views' => 6000, 'attack' => 1],
                        ['text' => 'تجربتي مع النخبة كانت عادية، لا سيء ولا ممتاز', 'sentiment' => 'neutral', 'score' => 50, 'rep' => 'neutral_mention', 'topic' => 'customer_experience', 'risk' => 10, 'likes' => 15, 'replies' => 3, 'reposts' => 2, 'views' => 800],
                        ['text' => 'النخبة توظف الآن! فرص وظيفية رائعة في مجال التقنية', 'sentiment' => 'positive', 'score' => 70, 'rep' => 'neutral_mention', 'topic' => 'hiring', 'risk' => 5, 'likes' => 60, 'replies' => 20, 'reposts' => 35, 'views' => 4000],
                        ['text' => 'مقاطعة النخبة فوراً! لا نثق بهذه الشركة بعد ما حدث #مقاطعة_النخبة', 'sentiment' => 'negative', 'score' => 8, 'rep' => 'attack', 'topic' => 'management', 'risk' => 85, 'likes' => 350, 'replies' => 120, 'reposts' => 90, 'views' => 25000, 'crisis' => 1, 'attack' => 1],
                        ['text' => 'أسعار النخبة مرتفعة مقارنة بالمنافسين لكن الجودة أفضل', 'sentiment' => 'neutral', 'score' => 45, 'rep' => 'neutral_mention', 'topic' => 'pricing', 'risk' => 25, 'likes' => 25, 'replies' => 10, 'reposts' => 5, 'views' => 1800],
                        ['text' => 'النخبة أعلنت عن شراكة استراتيجية جديدة، خطوة ممتازة!', 'sentiment' => 'positive', 'score' => 75, 'rep' => 'praise', 'topic' => 'management', 'risk' => 5, 'likes' => 80, 'replies' => 15, 'reposts' => 25, 'views' => 3500],
                        ['text' => 'شركة النخبة ما ترد على الشكاوى، هذا يدل على ضعف الإدارة', 'sentiment' => 'negative', 'score' => 25, 'rep' => 'complaint', 'topic' => 'management', 'risk' => 55, 'likes' => 100, 'replies' => 35, 'reposts' => 20, 'views' => 5000, 'complaint' => 1],
                        ['text' => 'إشاعة: النخبة على وشك الإفلاس! هل هذا صحيح؟', 'sentiment' => 'negative', 'score' => 12, 'rep' => 'rumor', 'topic' => 'management', 'risk' => 80, 'likes' => 200, 'replies' => 90, 'reposts' => 70, 'views' => 30000, 'crisis' => 1],
                        ['text' => 'خدمة التوصيل من النخبة تحسنت كثيرًا مؤخراً، شكراً لكم', 'sentiment' => 'positive', 'score' => 78, 'rep' => 'praise', 'topic' => 'service', 'risk' => 5, 'likes' => 55, 'replies' => 8, 'reposts' => 12, 'views' => 2200],
                        ['text' => 'المنافس الذهبي أفضل بكثير من النخبة، جربوه وما تندمون', 'sentiment' => 'negative', 'score' => 30, 'rep' => 'neutral_mention', 'topic' => 'competition', 'risk' => 40, 'likes' => 70, 'replies' => 25, 'reposts' => 15, 'views' => 4000],
                        ['text' => 'تصعيد: موظف في النخبة يتهم الإدارة بالتمييز والعنصرية!', 'sentiment' => 'negative', 'score' => 8, 'rep' => 'escalation', 'topic' => 'management', 'risk' => 88, 'likes' => 400, 'replies' => 150, 'reposts' => 100, 'views' => 40000, 'crisis' => 1, 'attack' => 1],
                        ['text' => 'الحملة الإعلانية الجديدة للنخبة إبداع، أعجبتني الفكرة', 'sentiment' => 'positive', 'score' => 82, 'rep' => 'praise', 'topic' => 'campaign', 'risk' => 5, 'likes' => 90, 'replies' => 12, 'reposts' => 30, 'views' => 5500],
                        ['text' => 'لماذا لا توجد قنوات تواصل واضحة لشركة النخبة؟', 'sentiment' => 'negative', 'score' => 30, 'rep' => 'complaint', 'topic' => 'support', 'risk' => 40, 'likes' => 60, 'replies' => 20, 'reposts' => 10, 'views' => 3000, 'complaint' => 1],
                        ['text' => 'جودة منتجات النخبة ممتازة بسعرهم شوي غالي', 'sentiment' => 'neutral', 'score' => 55, 'rep' => 'neutral_mention', 'topic' => 'quality', 'risk' => 15, 'likes' => 35, 'replies' => 8, 'reposts' => 5, 'views' => 1500],
                        ['text' => 'النخبة خسرت عميل وفي، لن أتعامل معهم مرة أخرى', 'sentiment' => 'negative', 'score' => 18, 'rep' => 'complaint', 'topic' => 'customer_experience', 'risk' => 50, 'likes' => 85, 'replies' => 30, 'reposts' => 18, 'views' => 4500, 'complaint' => 1],
                        ['text' => 'استفسار: هل النخبة تقدم خصومات للعملاء الدائمين؟', 'sentiment' => 'neutral', 'score' => 50, 'rep' => 'inquiry', 'topic' => 'pricing', 'risk' => 10, 'likes' => 20, 'replies' => 5, 'reposts' => 3, 'views' => 1200],
                        ['text' => 'النخبة تستحق التقدير على جهودها في خدمة المجتمع', 'sentiment' => 'positive', 'score' => 88, 'rep' => 'praise', 'topic' => 'general', 'risk' => 3, 'likes' => 110, 'replies' => 18, 'reposts' => 28, 'views' => 4200],
                        ['text' => 'هجوم منسق وواضح على حساب النخبة من حسابات جديدة بدون متابعين', 'sentiment' => 'negative', 'score' => 10, 'rep' => 'attack', 'topic' => 'management', 'risk' => 70, 'likes' => 150, 'replies' => 50, 'reposts' => 35, 'views' => 10000, 'attack' => 1],
                        ['text' => 'تجربتي مع دعم النخبة الفني كانت سلبية، انتظرت ساعتين بدون رد', 'sentiment' => 'negative', 'score' => 22, 'rep' => 'complaint', 'topic' => 'support', 'risk' => 45, 'likes' => 75, 'replies' => 28, 'reposts' => 12, 'views' => 3800, 'complaint' => 1],
                        ['text' => 'النخبة أطلقت تطبيق جديد، واجهة سهلة الاستخدام 👏', 'sentiment' => 'positive', 'score' => 80, 'rep' => 'praise', 'topic' => 'service', 'risk' => 5, 'likes' => 95, 'replies' => 10, 'reposts' => 22, 'views' => 3200],
                        ['text' => 'مقارنة بين النخبة والمنافس الذهبي: النخبة أفضل في الجودة', 'sentiment' => 'neutral', 'score' => 48, 'rep' => 'neutral_mention', 'topic' => 'competition', 'risk' => 20, 'likes' => 45, 'replies' => 15, 'reposts' => 8, 'views' => 2500],
                        ['text' => 'النخبة تماطل في رد الشكاوى وهذا يزيد من استفزاز العملاء', 'sentiment' => 'negative', 'score' => 20, 'rep' => 'escalation', 'topic' => 'customer_experience', 'risk' => 55, 'likes' => 130, 'replies' => 45, 'reposts' => 25, 'views' => 7000],
                        ['text' => 'عرض خاص من النخبة بمناسبة العيد، خصومات تصل إلى 30%', 'sentiment' => 'positive', 'score' => 72, 'rep' => 'neutral_mention', 'topic' => 'campaign', 'risk' => 5, 'likes' => 200, 'replies' => 25, 'reposts' => 50, 'views' => 8000],
                    ];

                    $authors = [
                        ['name' => 'أحمد الراشد', 'user' => 'ahmed_rashd', 'followers' => 15000, 'verified' => 1],
                        ['name' => 'سارة المحمد', 'user' => 'sara_mohmd', 'followers' => 25000, 'verified' => 1],
                        ['name' => 'خالد العتيبي', 'user' => 'khaled_otibi', 'followers' => 8000, 'verified' => 0],
                        ['name' => 'نورة السعيد', 'user' => 'noura_saeed', 'followers' => 45000, 'verified' => 1],
                        ['name' => 'محمد القحطاني', 'user' => 'mohmd_qahtani', 'followers' => 3200, 'verified' => 0],
                        ['name' => 'فاطمة الدوسري', 'user' => 'fatma_dosari', 'followers' => 12000, 'verified' => 0],
                        ['name' => 'عبدالله الشمري', 'user' => 'abdullah_shmri', 'followers' => 5000, 'verified' => 0],
                        ['name' => 'ريم الحربي', 'user' => 'reem_harbi', 'followers' => 18000, 'verified' => 1],
                        ['name' => 'حسام بوتفقة', 'user' => 'hussam_botfqa', 'followers' => 950, 'verified' => 0],
                        ['name' => 'ليلى الزهراني', 'user' => 'layla_zahrani', 'followers' => 6700, 'verified' => 0],
                    ];

                    foreach ($samplePosts as $i => $sp) {
                        $author = $authors[$i % count($authors)];
                        $postedAt = date('Y-m-d H:i:s', strtotime('-' . rand(1, 168) . ' hours'));

                        $postId = $db->insert('posts', [
                            'project_id' => $projectId,
                            'collection_run_id' => $runId,
                            'platform' => 'x_twitter',
                            'external_post_id' => 'mock_' . uniqid(),
                            'post_url' => 'https://x.com/' . $author['user'] . '/status/mock_' . $i,
                            'author_name' => $author['name'],
                            'author_username' => $author['user'],
                            'author_followers' => $author['followers'],
                            'author_verified' => $author['verified'],
                            'content_text' => $sp['text'],
                            'posted_at' => $postedAt,
                            'likes_count' => $sp['likes'],
                            'replies_count' => $sp['replies'],
                            'reposts_count' => $sp['reposts'],
                            'views_count' => $sp['views'],
                            'hashtags' => json_encode(['النخبة'], JSON_UNESCAPED_UNICODE),
                            'language' => 'ar',
                            'created_at' => date('Y-m-d H:i:s'),
                            'updated_at' => date('Y-m-d H:i:s')
                        ]);

                        $db->insert('post_ai_analysis', [
                            'post_id' => $postId,
                            'sentiment' => $sp['sentiment'],
                            'sentiment_score' => $sp['score'],
                            'reputation_label' => $sp['rep'],
                            'crisis_flag' => !empty($sp['crisis']) ? 1 : 0,
                            'attack_flag' => !empty($sp['attack']) ? 1 : 0,
                            'complaint_flag' => !empty($sp['complaint']) ? 1 : 0,
                            'sarcasm_flag' => !empty($sp['sarcasm']) ? 1 : 0,
                            'topic_label' => $sp['topic'],
                            'risk_score' => $sp['risk'],
                            'ai_summary' => 'تحليل: المنشور يتحدث عن ' . $sp['topic'] . ' بمشاعر ' . ($sp['sentiment'] === 'positive' ? 'إيجابية' : ($sp['sentiment'] === 'negative' ? 'سلبية' : 'محايدة')),
                            'ai_keywords' => json_encode(array_slice(explode(' ', $sp['text']), 0, 5), JSON_UNESCAPED_UNICODE),
                            'analysis_model' => 'mock-data',
                            'analyzed_at' => date('Y-m-d H:i:s')
                        ]);
                    }

                    // Sample alerts
                    $alerts = [
                        ['type' => 'negative_spike', 'severity' => 'high', 'title' => 'ارتفاع نسبة السلبية', 'desc' => 'نسبة المنشورات السلبية وصلت إلى 47%'],
                        ['type' => 'attack_detected', 'severity' => 'critical', 'title' => 'هجوم محتمل مكتشف', 'desc' => 'تم تصنيف 3 منشورات كهدجم خلال 24 ساعة'],
                        ['type' => 'crisis_keyword', 'severity' => 'high', 'title' => 'كلمة أزمة مكتشفة: مقاطعة النخبة', 'desc' => 'تكررت كلمة الأزمة 5 مرات خلال 24 ساعة'],
                        ['type' => 'complaint_surge', 'severity' => 'medium', 'title' => 'ارتفاع الشكاوى', 'desc' => 'تم رصد 6 شكاوى خلال 24 ساعة'],
                        ['type' => 'rumor_detected', 'severity' => 'high', 'title' => 'إشاعة مكتشفة', 'desc' => 'تم رصد إشاعة عن إفلاس الشركة'],
                    ];
                    foreach ($alerts as $alert) {
                        $db->insert('alerts', [
                            'project_id' => $projectId,
                            'alert_type' => $alert['type'],
                            'severity' => $alert['severity'],
                            'title' => $alert['title'],
                            'description' => $alert['desc'],
                            'evidence' => '{}',
                            'is_read' => 0,
                            'is_resolved' => 0,
                            'triggered_at' => date('Y-m-d H:i:s', strtotime('-' . rand(1, 48) . ' hours')),
                            'created_at' => date('Y-m-d H:i:s')
                        ]);
                    }

                    $success[] = 'تم إضافة 30 منشور تجريبي مع التحليلات';
                    $success[] = 'تم إضافة 5 تنبيهات تجريبية';
                } else {
                    $success[] = 'البيانات التجريبية موجودة مسبقاً';
                }
            }

            $_SESSION['install_complete'] = true;
        }
    }
}

// Start session for install state
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>تثبيت منصة الاستخبارات التسويقية</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: 'Segoe UI', Tahoma, Arial, sans-serif;
            background: linear-gradient(135deg, #1e293b 0%, #4f46e5 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
            direction: rtl;
        }
        .install-card {
            background: #fff;
            border-radius: 12px;
            width: 100%;
            max-width: 650px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.2);
            overflow: hidden;
        }
        .install-header {
            background: #4f46e5;
            color: #fff;
            padding: 30px;
            text-align: center;
        }
        .install-header h1 { font-size: 1.4rem; margin-bottom: 4px; }
        .install-header p { opacity: 0.8; font-size: 0.9rem; }
        .install-body { padding: 30px; }
        .steps {
            display: flex;
            justify-content: center;
            gap: 8px;
            margin-bottom: 30px;
        }
        .step-dot {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: 700;
            font-size: 0.85rem;
            background: #e2e8f0;
            color: #64748b;
            transition: all 0.3s;
        }
        .step-dot.active { background: #4f46e5; color: #fff; }
        .step-dot.done { background: #10b981; color: #fff; }
        .step-connector { width: 30px; height: 2px; background: #e2e8f0; align-self: center; }
        .step-connector.done { background: #10b981; }
        .form-group { margin-bottom: 18px; }
        .form-group label {
            display: block;
            font-size: 0.85rem;
            font-weight: 600;
            color: #334155;
            margin-bottom: 6px;
        }
        .form-control {
            width: 100%;
            padding: 10px 12px;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            font-size: 0.95rem;
            transition: border-color 0.2s;
            font-family: inherit;
        }
        .form-control:focus { outline: none; border-color: #4f46e5; box-shadow: 0 0 0 3px rgba(79,70,229,0.1); }
        .form-row { display: flex; gap: 12px; }
        .form-row > * { flex: 1; }
        .form-hint { font-size: 0.78rem; color: #94a3b8; margin-top: 4px; }
        .btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            padding: 12px 24px;
            border: none;
            border-radius: 8px;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s;
            width: 100%;
        }
        .btn-primary { background: #4f46e5; color: #fff; }
        .btn-primary:hover { background: #4338ca; }
        .btn-success { background: #10b981; color: #fff; }
        .btn-success:hover { background: #059669; }
        .alert {
            padding: 12px 16px;
            border-radius: 8px;
            margin-bottom: 16px;
            font-size: 0.9rem;
        }
        .alert-danger { background: #fee2e2; color: #991b1b; border: 1px solid #fecaca; }
        .alert-success { background: #d1fae5; color: #065f46; border: 1px solid #a7f3d0; }
        .alert-info { background: #e0e7ff; color: #3730a3; border: 1px solid #c7d2fe; }
        .checkbox-label { display: flex; align-items: center; gap: 8px; cursor: pointer; font-weight: normal; }
        .checkbox-label input { width: 18px; height: 18px; accent-color: #4f46e5; }
        .success-box { text-align: center; padding: 20px 0; }
        .success-box .icon { font-size: 3rem; color: #10b981; margin-bottom: 12px; }
        .success-box h2 { color: #1e293b; margin-bottom: 8px; }
        .success-box p { color: #64748b; margin-bottom: 6px; }
        .login-info {
            background: #f1f5f9;
            border-radius: 8px;
            padding: 16px;
            margin: 20px 0;
            text-align: center;
        }
        .login-info strong { color: #4f46e5; }
        .warning-box {
            background: #fef3c7;
            border: 1px solid #fde68a;
            border-radius: 8px;
            padding: 14px;
            margin: 16px 0;
            color: #92400e;
            font-size: 0.9rem;
        }
        @media (max-width: 600px) {
            .form-row { flex-direction: column; }
            .install-body { padding: 20px; }
        }
    </style>
</head>
<body>
    <div class="install-card">
        <div class="install-header">
            <h1>🚀 تثبيت منصة الاستخبارات التسويقية</h1>
            <p>Market Intelligence Platform Setup</p>
        </div>

        <div class="install-body">
            <!-- Steps indicator -->
            <div class="steps">
                <div class="step-dot <?= $step >= 1 ? ($step > 1 ? 'done' : 'active') : '' ?>">1</div>
                <div class="step-connector <?= $step > 1 ? 'done' : '' ?>"></div>
                <div class="step-dot <?= $step >= 2 ? ($step > 2 ? 'done' : 'active') : '' ?>">2</div>
                <div class="step-connector <?= $step > 2 ? 'done' : '' ?>"></div>
                <div class="step-dot <?= $step >= 3 ? ($step > 3 ? 'done' : 'active') : '' ?>">3</div>
                <div class="step-connector <?= $step > 3 ? 'done' : '' ?>"></div>
                <div class="step-dot <?= $step >= 4 ? 'active' : '' ?>">4</div>
            </div>

            <?php if (!empty($errors)): ?>
                <?php foreach ($errors as $err): ?>
                    <div class="alert alert-danger">✗ <?= htmlspecialchars($err) ?></div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if (!empty($success)): ?>
                <?php foreach ($success as $msg): ?>
                    <div class="alert alert-success">✓ <?= htmlspecialchars($msg) ?></div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if ($step === 1): ?>
            <!-- Step 1: Database Configuration -->
            <h3 style="margin-bottom:16px; color:#1e293b;">الخطوة 1: إعدادات قاعدة البيانات</h3>
            <form method="POST">
                <input type="hidden" name="step" value="2">
                <div class="form-group">
                    <label>مضيف قاعدة البيانات</label>
                    <input type="text" name="db_host" class="form-control" value="<?= htmlspecialchars($prefill['db_host']) ?>">
                </div>
                <div class="form-group">
                    <label>اسم قاعدة البيانات</label>
                    <input type="text" name="db_name" class="form-control" value="<?= htmlspecialchars($prefill['db_name']) ?>" required>
                    <div class="form-hint">سيتم إنشاؤها إذا لم تكن موجودة</div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label>اسم المستخدم</label>
                        <input type="text" name="db_user" class="form-control" value="<?= htmlspecialchars($prefill['db_user']) ?>" required>
                    </div>
                    <div class="form-group">
                        <label>كلمة المرور</label>
                        <input type="password" name="db_pass" class="form-control" value="<?= htmlspecialchars($prefill['db_pass']) ?>">
                    </div>
                </div>

                <hr style="margin: 20px 0; border-color: #e2e8f0;">

                <h3 style="margin-bottom:16px; color:#1e293b;">حساب المدير</h3>
                <div class="form-row">
                    <div class="form-group">
                        <label>اسم المستخدم</label>
                        <input type="text" name="admin_user" class="form-control" value="<?= htmlspecialchars($prefill['admin_user']) ?>" required>
                    </div>
                    <div class="form-group">
                        <label>كلمة المرور</label>
                        <input type="password" name="admin_pass" class="form-control" value="<?= htmlspecialchars($prefill['admin_pass']) ?>" required>
                    </div>
                </div>
                <div class="form-group">
                    <label>البريد الإلكتروني</label>
                    <input type="email" name="admin_email" class="form-control" value="<?= htmlspecialchars($prefill['admin_email']) ?>">
                </div>

                <button type="submit" class="btn btn-primary">
                    اختبار الاتصال وحفظ الإعدادات ←
                </button>
            </form>

            <?php elseif ($step === 2): ?>
            <!-- Step 2: Import Schema -->
            <h3 style="margin-bottom:16px; color:#1e293b;">الخطوة 2: إنشاء هيكل قاعدة البيانات</h3>
            <div class="alert alert-info">
                تم الاتصال بنجاح بقاعدة البيانات. الآن سيتم إنشاء الجداول.
            </div>
            <form method="POST">
                <input type="hidden" name="step" value="3">
                <button type="submit" class="btn btn-primary">
                    إنشاء الجداول الآن ←
                </button>
            </form>

            <?php elseif ($step === 3): ?>
            <!-- Step 3: Admin + Seed -->
            <h3 style="margin-bottom:16px; color:#1e293b;">الخطوة 3: إنشاء المدير والبيانات التجريبية</h3>
            <div class="alert alert-success">
                ✓ تم إنشاء هيكل قاعدة البيانات بنجاح (13 جدول)
            </div>
            <form method="POST">
                <input type="hidden" name="step" value="4">
                <div class="form-group">
                    <label class="checkbox-label">
                        <input type="checkbox" name="seed_data" value="1" checked>
                        إضافة بيانات تجريبية (30 منشور + تحليلات + تنبيهات)
                    </label>
                    <div class="form-hint">يُنصح به لاختبار المنصة قبل الاستخدام الفعلي</div>
                </div>
                <button type="submit" class="btn btn-primary">
                    إنهاء التثبيت ←
                </button>
            </form>

            <?php elseif ($step === 4 && !empty($_SESSION['install_complete'])): ?>
            <!-- Step 4: Complete -->
            <div class="success-box">
                <div class="icon">✅</div>
                <h2>تم التثبيت بنجاح!</h2>
                <p>منصة الاستخبارات التسويقية جاهزة للاستخدام</p>
            </div>

            <div class="login-info">
                <p>🔗 <strong>رابط الدخول:</strong> <a href="/login" style="color:#4f46e5;">/login</a></p>
                <p>👤 <strong>اسم المستخدم:</strong> <?= htmlspecialchars($_SESSION['install_db_user'] ?? $prefill['admin_user']) ?></p>
                <p>🔑 <strong>كلمة المرور:</strong> التي أدخلتها في الخطوة 1</p>
            </div>

            <div class="warning-box">
                ⚠️ <strong>مهم:</strong> احذف ملف install.php فوراً بعد التثبيت لأسباب أمنية!
            </div>

            <a href="/login" class="btn btn-success" style="text-decoration:none;">
                الدخول إلى لوحة التحكم ←
            </a>

            <?php endif; ?>
        </div>
    </div>
</body>
</html>
